clear all;
close all;
f=1000;
fs=100000;
N=5000;
ts=1/fs;
t=(0:ts:(N*ts)-ts);
f1=100;
m=sin(2*pi*f1*t);
kf=0.0628;
s=exp(j*(2*pi*f*t+2*pi*kf*cumsum(m)));
s1=exp(j*(2*pi*f*t));
phi_hat(1)=30;
e(1)=0;
phd_output(1)=0;
vco(1)=0;
kp=0.15;
ki=0.1;
for n=2:length(s)
    vco(n)=conj(exp(j*(2*pi*n*f/fs+phi_hat(n-1))));
    phd_output(n)=imag(s(n)*vco(n));
    e(n)=e(n-1)+(kp+ki)*phd_output(n)-ki*phd_output(n-1);
    phi_hat(n)=phi_hat(n-1)+e(n);
end;
startplot=1;
endplot=1000;
figure(1);
subplot(3,2,1);
plot(t(startplot:endplot),m(startplot:endplot));
title('100 hertz message singnal');
ylabel('amplitude');
grid on;
figure(1);
subplot(3,2,2);
plot(t(startplot:endplot),real(s(startplot:endplot)));
title('fm signal');
ylabel('amplitude');
grid on;
figure(1);
subplot(3,2,3);
plot(t(startplot:endplot),e(startplot:endplot));
title('Pll Loop circuit output');
ylabel('amplitude');
grid on;
subplot(3,2,4);
plot(t(startplot:endplot),real(vco(startplot:endplot)));
title('VCO output');
ylabel('amplitude');
grid on;
subplot(3,2,5);
plot(t(startplot:endplot),phd_output(startplot:endplot));
title('phase detector output');
ylabel('amplitude');
xlabel('time')
grid on;
subplot(3,2,6);
plot(t(startplot:endplot),real(s1(startplot:endplot)));
title('unmodulated carrier');
ylabel('amplitude');
xlabel('time');
grid on;